### ISSUE TITLE
어케쓰누?

### ISSUE THREAD

**Issue by Pneuma714** [thoratica/ticaOS#1]
바바바바ㅏ밥바바바ㅏ바바ㅏ밥

어디보자
케밥맛이
쓰레기네
누가했냐

**Comment by thoratica** [comment]
세로드립 ㄷ

**Comment by thoratica** [comment]
> 바바바바ㅏ밥바바바ㅏ바바ㅏ밥
> 
> 어디보자
> 케밥맛이
> 쓰레기네
> 누가했냐

`yarn start`나 `npm start` 하면 Electron 창이 열림.
`localhost:5500`으로도 접속 ㄱㄴ (Discord, Google 앱은 작동 안함)

**Comment by Pneuma714** [comment]
넴

**Comment by injoon5** [comment]
오류나네요
-----------------
(터미널)
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

새로운 크로스 플랫폼 PowerShell 사용 https://aka.ms/pscore6

PS C:\Users\injoo> cd C:\Users\injoo\Downloads\ticaOS-master
PS C:\Users\injoo\Downloads\ticaOS-master> yarn start
yarn run v1.22.4
$ nf start
17:06:38 react.1      |  'cross-env'��(��) ���� �Ǵ� �ܺ� ����, ������ �� �ִ� ���α׷�, �Ǵ�
17:06:38 react.1      |  ��ġ ������ �ƴմϴ�.
[DONE] Killing all processes with signal  SIGINT
17:06:38 react.1      Exited with exit code null
17:06:38 electron.1   Exited with exit code SIGINT
Done in 0.61s.
PS C:\Users\injoo\Downloads\ticaOS-master>
-----------------------------------------------------
nf 도 npm install -g foreman 으로 다운받았습니다.

**Comment by thoratica** [comment]
> 오류나네요
> -----------------
> (터미널)
> Windows PowerShell
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
> 새로운 크로스 플랫폼 PowerShell 사용 https://aka.ms/pscore6
> 
> PS C:\Users\injoo> cd C:\Users\injoo\Downloads\ticaOS-master
> PS C:\Users\injoo\Downloads\ticaOS-master> yarn start
> yarn run v1.22.4
> $ nf start
> 17:06:38 react.1      |  'cross-env'��(��) ���� �Ǵ� �ܺ� ����, ������ �� �ִ� ���α׷�, �Ǵ�
> 17:06:38 react.1      |  ��ġ ������ �ƴմϴ�.
> [DONE] Killing all processes with signal  SIGINT
> 17:06:38 react.1      Exited with exit code null
> 17:06:38 electron.1   Exited with exit code SIGINT
> Done in 0.61s.
> PS C:\Users\injoo\Downloads\ticaOS-master>
> -----------------------------------------------------
> nf 도 npm install -g foreman 으로 다운받았습니다.

`npm i -D cross-env` 가 필요합니다

**Comment by injoon5** [comment]
감사합니다~
제가 지금 모바일로 하고 있어서 내일 해보조록 하겠습니다. 😀
